"""empty message

Revision ID: 026ff8c5d681
Revises: 575381f929f6
Create Date: 2021-02-17 16:23:44.879902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '026ff8c5d681'
down_revision = '575381f929f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction_log', sa.Column('prod', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transaction_log', 'prod')
    # ### end Alembic commands ###
