"""empty message

Revision ID: 09126dc760ba
Revises: 9051498231cf
Create Date: 2021-10-15 11:03:52.722827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09126dc760ba'
down_revision = '9051498231cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('correo_cost', sa.String(length=15), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company', 'correo_cost')
    # ### end Alembic commands ###
