"""empty message

Revision ID: 0a52b473b6c7
Revises: 2b2f55ae9904
Create Date: 2021-01-29 11:00:14.138570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a52b473b6c7'
down_revision = '2b2f55ae9904'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_header', sa.Column('status_resumen', sa.String(length=15), nullable=True))
    op.add_column('transaction_log', sa.Column('status_client', sa.String(length=25), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transaction_log', 'status_client')
    op.drop_column('order_header', 'status_resumen')
    # ### end Alembic commands ###
