"""empty message

Revision ID: 0a53b8c23716
Revises: e5dd6d28e46a
Create Date: 2022-01-10 18:28:14.089890

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a53b8c23716'
down_revision = 'e5dd6d28e46a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('CONF_metodos_envios', sa.Column('correo_sucursal', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('CONF_metodos_envios', 'correo_sucursal')
    # ### end Alembic commands ###
