"""empty message

Revision ID: 0f3fea92bb2b
Revises: 3ab39f655469
Create Date: 2021-07-09 07:35:10.884489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f3fea92bb2b'
down_revision = '3ab39f655469'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_header', sa.Column('reject_reason', sa.String(length=350), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_header', 'reject_reason')
    # ### end Alembic commands ###
