"""empty message

Revision ID: 16c06262b3c4
Revises: 8b8a7d149a7f
Create Date: 2021-01-18 09:25:19.809471

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16c06262b3c4'
down_revision = '8b8a7d149a7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_detail', sa.Column('gestionado', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_detail', 'gestionado')
    # ### end Alembic commands ###
