"""empty message

Revision ID: 22c24c0fe2ca
Revises: 
Create Date: 2022-01-26 10:07:23.004725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22c24c0fe2ca'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('CONF_envios',
    sa.Column('store', sa.String(length=64), nullable=False),
    sa.Column('metodo_envio', sa.String(length=200), nullable=False),
    sa.Column('habilitado', sa.Boolean(), nullable=True),
    sa.Column('titulo_boton', sa.String(length=150), nullable=True),
    sa.Column('descripcion_boton', sa.String(length=350), nullable=True),
    sa.ForeignKeyConstraint(['store'], ['company.store_id'], ),
    sa.PrimaryKeyConstraint('store', 'metodo_envio')
    )
    op.add_column('order_header', sa.Column('etiqueta_generada', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_header', 'etiqueta_generada')
    op.drop_table('CONF_envios')
    # ### end Alembic commands ###
