"""empty message

Revision ID: 25bd081edbf6
Revises: 
Create Date: 2022-03-09 16:34:02.592990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25bd081edbf6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('CONF_correo', sa.Column('passw', sa.String(length=50), nullable=True))
    op.add_column('CONF_correo', sa.Column('user', sa.String(length=50), nullable=True))
    op.drop_column('company', 'confirma_moova_note')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('confirma_moova_note', sa.VARCHAR(length=500), nullable=True))
    op.drop_column('CONF_correo', 'user')
    op.drop_column('CONF_correo', 'passw')
    # ### end Alembic commands ###
