"""empty message

Revision ID: 27c7be69e351
Revises: 
Create Date: 2022-01-19 13:27:48.255418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27c7be69e351'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('store_id', sa.String(length=64), nullable=False),
    sa.Column('platform', sa.String(length=64), nullable=True),
    sa.Column('platform_token_type', sa.String(length=30), nullable=True),
    sa.Column('platform_access_token', sa.String(length=64), nullable=True),
    sa.Column('store_name', sa.String(length=120), nullable=True),
    sa.Column('store_main_language', sa.String(length=20), nullable=True),
    sa.Column('store_main_currency', sa.String(length=20), nullable=True),
    sa.Column('store_country', sa.String(length=20), nullable=True),
    sa.Column('store_url', sa.String(length=120), nullable=True),
    sa.Column('store_plan', sa.String(length=64), nullable=True),
    sa.Column('store_phone', sa.String(length=20), nullable=True),
    sa.Column('store_address', sa.String(length=120), nullable=True),
    sa.Column('admin_email', sa.String(length=120), nullable=True),
    sa.Column('communication_email', sa.String(length=120), nullable=True),
    sa.Column('communication_email_name', sa.String(length=120), nullable=True),
    sa.Column('param_logo', sa.String(length=200), nullable=True),
    sa.Column('param_fondo', sa.String(length=120), nullable=True),
    sa.Column('param_config', sa.String(length=120), nullable=True),
    sa.Column('contact_name', sa.String(length=64), nullable=True),
    sa.Column('contact_phone', sa.String(length=15), nullable=True),
    sa.Column('contact_email', sa.String(length=120), nullable=True),
    sa.Column('correo_usado', sa.String(length=64), nullable=True),
    sa.Column('correo_apikey', sa.String(length=50), nullable=True),
    sa.Column('correo_id', sa.String(length=50), nullable=True),
    sa.Column('correo_test', sa.Boolean(), nullable=True),
    sa.Column('correo_cost', sa.String(length=15), nullable=True),
    sa.Column('stock_vuelve_config', sa.Boolean(), nullable=True),
    sa.Column('correo_apikey_test', sa.String(length=50), nullable=True),
    sa.Column('correo_id_test', sa.String(length=50), nullable=True),
    sa.Column('shipping_address', sa.String(length=64), nullable=True),
    sa.Column('shipping_number', sa.String(length=64), nullable=True),
    sa.Column('shipping_floor', sa.String(length=64), nullable=True),
    sa.Column('shipping_zipcode', sa.String(length=64), nullable=True),
    sa.Column('shipping_city', sa.String(length=64), nullable=True),
    sa.Column('shipping_province', sa.String(length=64), nullable=True),
    sa.Column('shipping_country', sa.String(length=64), nullable=True),
    sa.Column('shipping_info', sa.String(length=120), nullable=True),
    sa.Column('aprobado_note', sa.String(length=250), nullable=True),
    sa.Column('rechazado_note', sa.String(length=250), nullable=True),
    sa.Column('envio_manual_note', sa.String(length=500), nullable=True),
    sa.Column('envio_coordinar_note', sa.String(length=500), nullable=True),
    sa.Column('envio_correo_note', sa.String(length=500), nullable=True),
    sa.Column('cupon_generado_note', sa.String(length=350), nullable=True),
    sa.Column('finalizado_note', sa.String(length=500), nullable=True),
    sa.Column('confirma_manual_note', sa.String(length=500), nullable=True),
    sa.Column('confirma_coordinar_note', sa.String(length=500), nullable=True),
    sa.Column('confirma_moova_note', sa.String(length=500), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('demo_store', sa.Boolean(), nullable=True),
    sa.Column('rubro_tienda', sa.String(length=64), nullable=True),
    sa.Column('plan_boris', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('store_id')
    )
    op.create_index(op.f('ix_company_platform'), 'company', ['platform'], unique=False)
    op.create_index(op.f('ix_company_store_id'), 'company', ['store_id'], unique=False)
    op.create_table('correos',
    sa.Column('correo_id', sa.String(length=15), nullable=False),
    sa.Column('correo_descripcion', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('correo_id')
    )
    op.create_table('customer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('identification', sa.String(length=20), nullable=True),
    sa.Column('phone', sa.String(length=15), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_email'), 'customer', ['email'], unique=False)
    op.create_index(op.f('ix_customer_name'), 'customer', ['name'], unique=False)
    op.create_index(op.f('ix_customer_platform'), 'customer', ['platform'], unique=False)
    op.create_table('metodos_envios',
    sa.Column('metodo_envio_id', sa.String(length=20), nullable=False),
    sa.Column('metodo_envio_descripcion', sa.String(length=200), nullable=True),
    sa.Column('carrier', sa.Boolean(), nullable=True),
    sa.Column('direccion_obligatoria', sa.Boolean(), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('metodo_envio_id')
    )
    op.create_table('CONF_boris',
    sa.Column('store', sa.String(length=64), nullable=False),
    sa.Column('ventana_cambios', sa.Integer(), nullable=True),
    sa.Column('ventana_devolucion', sa.Integer(), nullable=True),
    sa.Column('cambio_otra_cosa', sa.Boolean(), nullable=True),
    sa.Column('cambio_cupon', sa.Boolean(), nullable=True),
    sa.Column('cambio_opcion', sa.String(length=150), nullable=True),
    sa.Column('cambio_opcion_cupon', sa.String(length=150), nullable=True),
    sa.Column('cambio_opcion_otra_cosa', sa.String(length=150), nullable=True),
    sa.Column('portal_empresa', sa.String(length=150), nullable=True),
    sa.Column('portal_titulo', sa.String(length=250), nullable=True),
    sa.Column('portal_texto', sa.String(length=250), nullable=True),
    sa.ForeignKeyConstraint(['store'], ['company.store_id'], ),
    sa.PrimaryKeyConstraint('store')
    )
    op.create_table('CONF_correo',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('store', sa.String(length=64), nullable=True),
    sa.Column('correo_id', sa.String(length=15), nullable=True),
    sa.Column('cliente_apikey', sa.String(length=100), nullable=True),
    sa.Column('cliente_id', sa.String(length=50), nullable=True),
    sa.Column('habilitado', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['correo_id'], ['correos.correo_id'], ),
    sa.ForeignKeyConstraint(['store'], ['company.store_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('CONF_metodos_envios',
    sa.Column('store', sa.String(length=64), nullable=False),
    sa.Column('metodo_envio_id', sa.String(length=20), nullable=False),
    sa.Column('habilitado', sa.Boolean(), nullable=True),
    sa.Column('titulo_boton', sa.String(length=150), nullable=True),
    sa.Column('descripcion_boton', sa.String(length=350), nullable=True),
    sa.Column('correo_id', sa.String(length=10), nullable=True),
    sa.Column('correo_descripcion', sa.String(length=150), nullable=True),
    sa.Column('correo_servicio', sa.String(length=50), nullable=True),
    sa.Column('correo_sucursal', sa.String(length=50), nullable=True),
    sa.Column('costo_envio', sa.String(length=15), nullable=True),
    sa.Column('instrucciones_entrega', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['metodo_envio_id'], ['metodos_envios.metodo_envio_id'], ),
    sa.ForeignKeyConstraint(['store'], ['company.store_id'], ),
    sa.PrimaryKeyConstraint('store', 'metodo_envio_id')
    )
    op.create_table('CONF_motivos',
    sa.Column('store', sa.String(length=64), nullable=False),
    sa.Column('id_motivo', sa.Integer(), nullable=False),
    sa.Column('motivo', sa.String(length=35), nullable=True),
    sa.Column('tipo_motivo', sa.String(length=35), nullable=True),
    sa.ForeignKeyConstraint(['store'], ['company.store_id'], ),
    sa.PrimaryKeyConstraint('store', 'id_motivo')
    )
    op.create_table('categories_filter',
    sa.Column('store', sa.String(length=64), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('category_desc', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['store'], ['company.store_id'], ),
    sa.PrimaryKeyConstraint('store', 'category_id')
    )
    op.create_table('order_header',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_number', sa.Integer(), nullable=True),
    sa.Column('order_id_anterior', sa.Integer(), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.Column('date_closed', sa.DateTime(), nullable=True),
    sa.Column('date_lastupdate', sa.DateTime(), nullable=True),
    sa.Column('gastos_cupon', sa.Float(), nullable=True),
    sa.Column('salientes', sa.String(length=10), nullable=True),
    sa.Column('gastos_gateway', sa.Float(), nullable=True),
    sa.Column('gastos_shipping_owner', sa.Float(), nullable=True),
    sa.Column('gastos_shipping_customer', sa.Float(), nullable=True),
    sa.Column('gastos_promocion', sa.Float(), nullable=True),
    sa.Column('payment_method', sa.String(length=35), nullable=True),
    sa.Column('payment_card', sa.String(length=35), nullable=True),
    sa.Column('courier_method', sa.String(length=64), nullable=True),
    sa.Column('metodo_envio_correo', sa.String(length=64), nullable=True),
    sa.Column('metodo_envio_guia', sa.String(length=64), nullable=True),
    sa.Column('courier_precio', sa.String(length=20), nullable=True),
    sa.Column('courier_coordinar_empresa', sa.String(length=120), nullable=True),
    sa.Column('courier_coordinar_guia', sa.String(length=64), nullable=True),
    sa.Column('courier_coordinar_roundtrip', sa.Boolean(), nullable=True),
    sa.Column('nuevo_envio', sa.String(length=100), nullable=True),
    sa.Column('nuevo_envio_costo', sa.Float(), nullable=True),
    sa.Column('nuevo_envio_total', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=25), nullable=True),
    sa.Column('sub_status', sa.String(length=25), nullable=True),
    sa.Column('status_resumen', sa.String(length=25), nullable=True),
    sa.Column('reject_reason', sa.String(length=350), nullable=True),
    sa.Column('customer_address', sa.String(length=64), nullable=True),
    sa.Column('customer_number', sa.String(length=35), nullable=True),
    sa.Column('customer_floor', sa.String(length=64), nullable=True),
    sa.Column('customer_zipcode', sa.String(length=8), nullable=True),
    sa.Column('customer_locality', sa.String(length=250), nullable=True),
    sa.Column('customer_city', sa.String(length=64), nullable=True),
    sa.Column('customer_province', sa.String(length=64), nullable=True),
    sa.Column('customer_country', sa.String(length=64), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('store', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['store'], ['company.store_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_header_metodo_envio_guia'), 'order_header', ['metodo_envio_guia'], unique=False)
    op.create_index(op.f('ix_order_header_order_number'), 'order_header', ['order_number'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('identification', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('store', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['store'], ['company.store_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=False)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_index(op.f('ix_user_identification'), 'user', ['identification'], unique=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('order_detail',
    sa.Column('order_line_number', sa.String(length=30), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=True),
    sa.Column('prod_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('variant', sa.Integer(), nullable=True),
    sa.Column('accion', sa.String(length=10), nullable=True),
    sa.Column('accion_cambiar_por', sa.Integer(), nullable=True),
    sa.Column('accion_cambiar_por_prod_id', sa.Integer(), nullable=True),
    sa.Column('accion_cambiar_por_desc', sa.String(length=120), nullable=True),
    sa.Column('accion_cantidad', sa.Integer(), nullable=True),
    sa.Column('motivo', sa.String(length=50), nullable=True),
    sa.Column('monto_a_devolver', sa.Float(), nullable=True),
    sa.Column('monto_devuelto', sa.Float(), nullable=True),
    sa.Column('nuevo_envio', sa.String(length=100), nullable=True),
    sa.Column('restock', sa.String(length=30), nullable=True),
    sa.Column('precio', sa.Float(), nullable=True),
    sa.Column('alto', sa.Float(), nullable=True),
    sa.Column('largo', sa.Float(), nullable=True),
    sa.Column('profundidad', sa.Float(), nullable=True),
    sa.Column('peso', sa.Float(), nullable=True),
    sa.Column('promo_descuento', sa.Float(), nullable=True),
    sa.Column('promo_nombre', sa.String(length=120), nullable=True),
    sa.Column('promo_precio_final', sa.Float(), nullable=True),
    sa.Column('gestionado', sa.String(length=10), nullable=True),
    sa.Column('fecha_gestionado', sa.DateTime(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['order'], ['order_header.id'], ),
    sa.PrimaryKeyConstraint('order_line_number')
    )
    op.create_table('transaction_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sub_status', sa.String(length=15), nullable=True),
    sa.Column('status_client', sa.String(length=25), nullable=True),
    sa.Column('prod', sa.String(length=64), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['order_header.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaction_log')
    op.drop_table('order_detail')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_identification'), table_name='user')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_order_header_order_number'), table_name='order_header')
    op.drop_index(op.f('ix_order_header_metodo_envio_guia'), table_name='order_header')
    op.drop_table('order_header')
    op.drop_table('categories_filter')
    op.drop_table('CONF_motivos')
    op.drop_table('CONF_metodos_envios')
    op.drop_table('CONF_correo')
    op.drop_table('CONF_boris')
    op.drop_table('metodos_envios')
    op.drop_index(op.f('ix_customer_platform'), table_name='customer')
    op.drop_index(op.f('ix_customer_name'), table_name='customer')
    op.drop_index(op.f('ix_customer_email'), table_name='customer')
    op.drop_table('customer')
    op.drop_table('correos')
    op.drop_index(op.f('ix_company_store_id'), table_name='company')
    op.drop_index(op.f('ix_company_platform'), table_name='company')
    op.drop_table('company')
    # ### end Alembic commands ###
