"""empty message

Revision ID: 2b2f55ae9904
Revises: 118943eb1caf
Create Date: 2021-01-28 17:05:45.256926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b2f55ae9904'
down_revision = '118943eb1caf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_header', sa.Column('courier_precio', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_header', 'courier_precio')
    # ### end Alembic commands ###
