"""empty message

Revision ID: 31bb2110a497
Revises: b5de7fed178a
Create Date: 2022-03-15 11:37:00.718355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31bb2110a497'
down_revision = 'b5de7fed178a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('CONF_boris', sa.Column('observaciones', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('CONF_boris', 'observaciones')
    # ### end Alembic commands ###
