"""empty message

Revision ID: 34e8619e9138
Revises: 165d8e43e23b
Create Date: 2021-03-29 10:15:54.923319

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34e8619e9138'
down_revision = '165d8e43e23b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('correo_apikey_test', sa.String(length=50), nullable=True))
    op.add_column('company', sa.Column('correo_id_test', sa.String(length=50), nullable=True))
    op.add_column('company', sa.Column('correo_test', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company', 'correo_test')
    op.drop_column('company', 'correo_id_test')
    op.drop_column('company', 'correo_apikey_test')
    # ### end Alembic commands ###
