"""empty message

Revision ID: 392cf8172cc2
Revises: 9b86d086e9f3
Create Date: 2021-02-18 18:44:55.894999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '392cf8172cc2'
down_revision = '9b86d086e9f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_detail', sa.Column('nuevo_envio', sa.String(length=15), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_detail', 'nuevo_envio')
    # ### end Alembic commands ###
