"""empty message

Revision ID: 3ab39f655469
Revises: 96a3b63437a0
Create Date: 2021-07-06 20:16:49.106143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ab39f655469'
down_revision = '96a3b63437a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('confirma_coordinar_note', sa.String(length=350), nullable=True))
    op.add_column('company', sa.Column('confirma_manual_note', sa.String(length=350), nullable=True))
    op.add_column('company', sa.Column('confirma_moova_note', sa.String(length=350), nullable=True))
    op.add_column('company', sa.Column('start_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company', 'start_date')
    op.drop_column('company', 'confirma_moova_note')
    op.drop_column('company', 'confirma_manual_note')
    op.drop_column('company', 'confirma_coordinar_note')
    # ### end Alembic commands ###
