"""empty message

Revision ID: 3c00d5e13f62
Revises: d3d3a94a13d9
Create Date: 2021-04-21 16:58:17.182216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c00d5e13f62'
down_revision = 'd3d3a94a13d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company', 'store_name_bis')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('store_name_bis', sa.VARCHAR(length=120), nullable=True))
    # ### end Alembic commands ###
