"""empty message

Revision ID: 475867806c71
Revises: 0a53b8c23716
Create Date: 2022-01-12 14:47:10.034709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '475867806c71'
down_revision = '0a53b8c23716'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_header', sa.Column('salientes', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_header', 'salientes')
    # ### end Alembic commands ###
