"""empty message

Revision ID: 52591ada7d54
Revises: 35bd62821cd5
Create Date: 2021-02-12 08:21:16.691162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52591ada7d54'
down_revision = '35bd62821cd5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_header', sa.Column('date_creation', sa.DateTime(), nullable=True))
    op.add_column('order_header', sa.Column('date_lastupdate', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_header', 'date_lastupdate')
    op.drop_column('order_header', 'date_creation')
    # ### end Alembic commands ###
