"""empty message

Revision ID: 535faa034693
Revises: b56b697c56e1
Create Date: 2022-02-10 08:43:47.876131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '535faa034693'
down_revision = 'b56b697c56e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('confirma_retiro_note', sa.String(length=500), nullable=True))
    op.add_column('company', sa.Column('store_idfiscal', sa.String(length=20), nullable=True))
    op.drop_column('company', 'confirma_moova_note')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('confirma_moova_note', sa.VARCHAR(length=500), nullable=True))
    op.drop_column('company', 'store_idfiscal')
    op.drop_column('company', 'confirma_retiro_note')
    # ### end Alembic commands ###
