"""empty message

Revision ID: 569bc5efa790
Revises: d558281ff19b
Create Date: 2022-01-04 16:31:17.298435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '569bc5efa790'
down_revision = 'd558281ff19b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('CONF_metodos_envios', sa.Column('costo_envio', sa.String(length=15), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('CONF_metodos_envios', 'costo_envio')
    # ### end Alembic commands ###
