"""empty message

Revision ID: 6368a3315bfe
Revises: 09126dc760ba
Create Date: 2021-10-15 16:55:53.200996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6368a3315bfe'
down_revision = '09126dc760ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('CONF_boris', sa.Column('cambio_opcion', sa.String(length=100), nullable=True))
    op.add_column('CONF_boris', sa.Column('cambio_opcion_cupon', sa.String(length=100), nullable=True))
    op.add_column('CONF_boris', sa.Column('cambio_opcion_otra_cosa', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('CONF_boris', 'cambio_opcion_otra_cosa')
    op.drop_column('CONF_boris', 'cambio_opcion_cupon')
    op.drop_column('CONF_boris', 'cambio_opcion')
    # ### end Alembic commands ###
