"""empty message

Revision ID: 70882247c437
Revises: abd37fec9233
Create Date: 2021-12-10 10:07:50.148813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70882247c437'
down_revision = 'abd37fec9233'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('communication_email_name', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company', 'communication_email_name')
    # ### end Alembic commands ###
