"""empty message

Revision ID: 739db3d49778
Revises: 73ae64a901fe
Create Date: 2021-05-10 14:51:11.784911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '739db3d49778'
down_revision = '73ae64a901fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_header', sa.Column('courier_coordinar_empresa', sa.String(length=120), nullable=True))
    op.add_column('order_header', sa.Column('courier_coordinar_guia', sa.String(length=64), nullable=True))
    op.add_column('order_header', sa.Column('courier_coordinar_roundtrip', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_header', 'courier_coordinar_roundtrip')
    op.drop_column('order_header', 'courier_coordinar_guia')
    op.drop_column('order_header', 'courier_coordinar_empresa')
    # ### end Alembic commands ###
