"""empty message

Revision ID: 7b6777f9145f
Revises: 392cf8172cc2
Create Date: 2021-02-19 09:56:27.021232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b6777f9145f'
down_revision = '392cf8172cc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_detail', sa.Column('fecha_gestionado', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_detail', 'fecha_gestionado')
    # ### end Alembic commands ###
