"""empty message

Revision ID: 869fbbccaf08
Revises: e141aa061394
Create Date: 2021-06-03 14:25:28.660647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '869fbbccaf08'
down_revision = 'e141aa061394'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('envio_coordinar_note', sa.String(length=250), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company', 'envio_coordinar_note')
    # ### end Alembic commands ###
