"""empty message

Revision ID: 8b8a7d149a7f
Revises: e6140580ce38
Create Date: 2021-01-17 19:18:00.786337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b8a7d149a7f'
down_revision = 'e6140580ce38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction_log', sa.Column('username', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transaction_log', 'username')
    # ### end Alembic commands ###
