"""empty message

Revision ID: 96a3b63437a0
Revises: a7bf18c6743b
Create Date: 2021-06-21 10:38:14.403647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96a3b63437a0'
down_revision = 'a7bf18c6743b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories_filter',
    sa.Column('store', sa.String(length=64), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('category_desc', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['store'], ['company.store_id'], ),
    sa.PrimaryKeyConstraint('category_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('categories_filter')
    # ### end Alembic commands ###
