"""empty message

Revision ID: 9a7199f76d8e
Revises: 0a52b473b6c7
Create Date: 2021-02-02 11:55:28.281412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a7199f76d8e'
down_revision = '0a52b473b6c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_detail', sa.Column('accion_cambiar_por_desc', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_detail', 'accion_cambiar_por_desc')
    # ### end Alembic commands ###
