"""empty message

Revision ID: 9e5e50efb90b
Revises: 
Create Date: 2021-01-16 18:40:23.668325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e5e50efb90b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('store_id', sa.String(length=64), nullable=False),
    sa.Column('platform', sa.String(length=64), nullable=True),
    sa.Column('store_name', sa.String(length=64), nullable=True),
    sa.Column('admin_email', sa.String(length=120), nullable=True),
    sa.Column('param_logo', sa.String(length=120), nullable=True),
    sa.Column('param_fondo', sa.String(length=120), nullable=True),
    sa.Column('param_config', sa.String(length=120), nullable=True),
    sa.Column('contact_name', sa.String(length=64), nullable=True),
    sa.Column('contact_phone', sa.String(length=15), nullable=True),
    sa.Column('contact_email', sa.String(length=120), nullable=True),
    sa.Column('correo_usado', sa.String(length=64), nullable=True),
    sa.Column('correo_apikey', sa.String(length=50), nullable=True),
    sa.Column('correo_id', sa.String(length=50), nullable=True),
    sa.Column('shipping_address', sa.String(length=64), nullable=True),
    sa.Column('shipping_number', sa.String(length=64), nullable=True),
    sa.Column('shipping_floor', sa.String(length=64), nullable=True),
    sa.Column('shipping_zipcode', sa.String(length=64), nullable=True),
    sa.Column('shipping_city', sa.String(length=64), nullable=True),
    sa.Column('shipping_province', sa.String(length=64), nullable=True),
    sa.Column('shipping_country', sa.String(length=64), nullable=True),
    sa.Column('shipping_info', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('store_id')
    )
    op.create_index(op.f('ix_company_platform'), 'company', ['platform'], unique=False)
    op.create_index(op.f('ix_company_store_id'), 'company', ['store_id'], unique=False)
    op.create_table('customer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=15), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_email'), 'customer', ['email'], unique=True)
    op.create_index(op.f('ix_customer_name'), 'customer', ['name'], unique=False)
    op.create_index(op.f('ix_customer_platform'), 'customer', ['platform'], unique=False)
    op.create_table('order_header',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_number', sa.Integer(), nullable=True),
    sa.Column('order_id_anterior', sa.Integer(), nullable=True),
    sa.Column('creation_date', sa.String(length=35), nullable=True),
    sa.Column('last_update_date', sa.String(length=35), nullable=True),
    sa.Column('payment_method', sa.String(length=10), nullable=True),
    sa.Column('payment_card', sa.String(length=10), nullable=True),
    sa.Column('courier_order_id', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=15), nullable=True),
    sa.Column('sub_status', sa.String(length=15), nullable=True),
    sa.Column('customer_address', sa.String(length=64), nullable=True),
    sa.Column('customer_number', sa.String(length=10), nullable=True),
    sa.Column('customer_floor', sa.String(length=10), nullable=True),
    sa.Column('customer_zipcode', sa.String(length=8), nullable=True),
    sa.Column('customer_locality', sa.String(length=64), nullable=True),
    sa.Column('customer_city', sa.String(length=64), nullable=True),
    sa.Column('customer_province', sa.String(length=64), nullable=True),
    sa.Column('customer_country', sa.String(length=64), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('store', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['store'], ['company.store_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_header_courier_order_id'), 'order_header', ['courier_order_id'], unique=False)
    op.create_index(op.f('ix_order_header_creation_date'), 'order_header', ['creation_date'], unique=False)
    op.create_index(op.f('ix_order_header_order_number'), 'order_header', ['order_number'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('store', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['store'], ['company.store_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('order_detail',
    sa.Column('order_line_number', sa.String(), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=True),
    sa.Column('prod_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('accion', sa.String(length=10), nullable=True),
    sa.Column('accion_cambiar_por', sa.Integer(), nullable=True),
    sa.Column('accion_cantidad', sa.Integer(), nullable=True),
    sa.Column('motivo', sa.String(length=50), nullable=True),
    sa.Column('monto_a_devolver', sa.Float(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['order'], ['order_header.id'], ),
    sa.PrimaryKeyConstraint('order_line_number')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_detail')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_order_header_order_number'), table_name='order_header')
    op.drop_index(op.f('ix_order_header_creation_date'), table_name='order_header')
    op.drop_index(op.f('ix_order_header_courier_order_id'), table_name='order_header')
    op.drop_table('order_header')
    op.drop_index(op.f('ix_customer_platform'), table_name='customer')
    op.drop_index(op.f('ix_customer_name'), table_name='customer')
    op.drop_index(op.f('ix_customer_email'), table_name='customer')
    op.drop_table('customer')
    op.drop_index(op.f('ix_company_store_id'), table_name='company')
    op.drop_index(op.f('ix_company_platform'), table_name='company')
    op.drop_table('company')
    # ### end Alembic commands ###
