"""empty message

Revision ID: 9f07f1fe45ff
Revises: 6368a3315bfe
Create Date: 2021-10-18 14:49:47.419026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f07f1fe45ff'
down_revision = '6368a3315bfe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('demo_store', sa.Boolean(), nullable=True))
    op.add_column('company', sa.Column('rubro_tienda', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company', 'rubro_tienda')
    op.drop_column('company', 'demo_store')
    # ### end Alembic commands ###
