"""empty message

Revision ID: a3ba884528c0
Revises: 0f3fea92bb2b
Create Date: 2021-07-16 15:17:07.592170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3ba884528c0'
down_revision = '0f3fea92bb2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_header', sa.Column('note', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_header', 'note')
    # ### end Alembic commands ###
