"""empty message

Revision ID: a7bf18c6743b
Revises: b4d14071ecb3
Create Date: 2021-06-04 17:41:54.520957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7bf18c6743b'
down_revision = 'b4d14071ecb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('cupon_generado_note', sa.String(length=250), nullable=True))
    op.add_column('company', sa.Column('rechazado_note', sa.String(length=250), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company', 'rechazado_note')
    op.drop_column('company', 'cupon_generado_note')
    # ### end Alembic commands ###
