"""empty message

Revision ID: abd37fec9233
Revises: 9f07f1fe45ff
Create Date: 2021-11-19 09:30:15.349044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abd37fec9233'
down_revision = '9f07f1fe45ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('plan_boris', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company', 'plan_boris')
    # ### end Alembic commands ###
