"""empty message

Revision ID: b4d14071ecb3
Revises: 869fbbccaf08
Create Date: 2021-06-04 09:22:21.919684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4d14071ecb3'
down_revision = '869fbbccaf08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('aprobado_note', sa.String(length=250), nullable=True))
    op.add_column('company', sa.Column('envio_correo_note', sa.String(length=250), nullable=True))
    op.add_column('company', sa.Column('finalizado_note', sa.String(length=250), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company', 'finalizado_note')
    op.drop_column('company', 'envio_correo_note')
    op.drop_column('company', 'aprobado_note')
    # ### end Alembic commands ###
