"""empty message

Revision ID: b56b697c56e1
Revises: 22c24c0fe2ca
Create Date: 2022-01-28 07:54:31.529162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b56b697c56e1'
down_revision = '22c24c0fe2ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('correos', sa.Column('correo_mail', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('correos', 'correo_mail')
    # ### end Alembic commands ###
