"""empty message

Revision ID: bb2e959b7c07
Revises: 
Create Date: 2022-03-24 17:30:14.992522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb2e959b7c07'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('CONF_boris', sa.Column('observaciones', sa.Boolean(), nullable=True))
    op.add_column('CONF_correo', sa.Column('passw', sa.String(length=50), nullable=True))
    op.add_column('CONF_correo', sa.Column('user', sa.String(length=50), nullable=True))
    op.drop_column('company', 'confirma_moova_note')
    op.add_column('order_detail', sa.Column('observaciones', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_detail', 'observaciones')
    op.add_column('company', sa.Column('confirma_moova_note', sa.VARCHAR(length=500), nullable=True))
    op.drop_column('CONF_correo', 'user')
    op.drop_column('CONF_correo', 'passw')
    op.drop_column('CONF_boris', 'observaciones')
    # ### end Alembic commands ###
