"""empty message

Revision ID: bee7e003e6f2
Revises: d2024d370515
Create Date: 2021-04-02 09:44:05.961329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bee7e003e6f2'
down_revision = 'd2024d370515'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('platform_access_token', sa.String(length=64), nullable=True))
    op.add_column('company', sa.Column('platform_token_type', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company', 'platform_token_type')
    op.drop_column('company', 'platform_access_token')
    # ### end Alembic commands ###
