"""empty message

Revision ID: d050de9007da
Revises: a3ba884528c0
Create Date: 2021-07-27 08:20:19.864162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd050de9007da'
down_revision = 'a3ba884528c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_detail', sa.Column('accion_cambiar_por_prod_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_detail', 'accion_cambiar_por_prod_id')
    # ### end Alembic commands ###
