"""empty message

Revision ID: d2024d370515
Revises: 34e8619e9138
Create Date: 2021-04-01 13:09:39.426338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2024d370515'
down_revision = '34e8619e9138'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('communication_email', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company', 'communication_email')
    # ### end Alembic commands ###
