"""empty message

Revision ID: d3d3a94a13d9
Revises: 60880ea3d795
Create Date: 2021-04-21 15:20:14.111762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3d3a94a13d9'
down_revision = '60880ea3d795'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('store_address', sa.String(length=120), nullable=True))
    op.add_column('company', sa.Column('store_name_bis', sa.String(length=120), nullable=True))
    op.add_column('company', sa.Column('store_phone', sa.String(length=15), nullable=True))
    op.add_column('company', sa.Column('store_plan', sa.String(length=64), nullable=True))
    op.add_column('company', sa.Column('store_url', sa.String(length=120), nullable=True))
    op.drop_index('ix_customer_email', table_name='customer')
    op.create_index(op.f('ix_customer_email'), 'customer', ['email'], unique=False)
    op.drop_index('ix_user_email', table_name='user')
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.create_index('ix_user_email', 'user', ['email'], unique=1)
    op.drop_index(op.f('ix_customer_email'), table_name='customer')
    op.create_index('ix_customer_email', 'customer', ['email'], unique=1)
    op.drop_column('company', 'store_url')
    op.drop_column('company', 'store_plan')
    op.drop_column('company', 'store_phone')
    op.drop_column('company', 'store_name_bis')
    op.drop_column('company', 'store_address')
    # ### end Alembic commands ###
