"""empty message

Revision ID: e141aa061394
Revises: 739db3d49778
Create Date: 2021-06-03 11:00:15.414788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e141aa061394'
down_revision = '739db3d49778'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('envio_manual_note', sa.String(length=250), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company', 'envio_manual_note')
    # ### end Alembic commands ###
