"""empty message

Revision ID: eeec60351a57
Revises: 52591ada7d54
Create Date: 2021-02-12 17:53:47.681696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eeec60351a57'
down_revision = '52591ada7d54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_header', sa.Column('courier_method', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_header', 'courier_method')
    # ### end Alembic commands ###
