"""empty message

Revision ID: f866303ea286
Revises: cb7e365313f4
Create Date: 2021-09-06 12:59:20.129332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f866303ea286'
down_revision = 'cb7e365313f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_header', sa.Column('date_closed', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_header', 'date_closed')
    # ### end Alembic commands ###
